name: Unit Test

on:
  - push

jobs:
  run:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: ['8.2', '8.3', '8.4']
        laravel-version: ['11.0', '12.0']

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      - uses: actions/checkout@v2

      - name: Install laravel
        run: composer require illuminate/contracts:${{ matrix.laravel-version }} --no-interaction --prefer-dist --no-progress

      - name: Run unit tests
        run: vendor/bin/phpunit
